---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    elb_secgroup_rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8443
        to_port: 8443
        cidr_ip: 0.0.0.0/0
    instance_secgroup_rules:
      - proto: tcp
        from_port: 122
        to_port: 122
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        group_name: 'elb-secgroup'
      - proto: tcp
        from_port: 443
        to_port: 443
        group_name: 'elb-secgroup'
      - proto: tcp
        from_port: 8443
        to_port: 8443
        group_name: 'elb-secgroup'

  roles:
    -
      role: ec2-secgroups
      name: 'elb-secgroup'
      description: 'elb secgroup'
      rules: "{{ elb_secgroup_rules }}"
    -
      role: ec2-secgroups
      name: 'instance-secgroup'
      description: 'instance secgroup'
      rules: "{{ instance_secgroup_rules }}"
    -
      role: ec2-launchconfig
      name: 'ghes-launchconfig'
      state: 'present'
      image_id: 'ami-3b54c44c'
      instance_monitoring: 'yes'
      instance_profile_name: 'arn:aws:iam::675228244484:instance-profile/aws-full'
      instance_type: 'r3.large'
      security_groups: [ 'sg-4ee0982b' ] # FIXME - lookup secgroup ID dynamically.
      volumes:
        - device_name: '/dev/xvdf'
          volume_size: '10'
          device_type: 'standard'
      user_data: "#!/bin/bash \n
                  apt-get -y update \n
                  apt-get -y upgrade"
    -
      role: ec2-autoscaling
      name: 'ghes-asg'
      state: 'present'
      availability_zones: [ 'eu-west-1a' ]
      desired_capacity: '1'
      max_size: '1'
      min_size: '1'
      launch_config_name: 'ghes-launchconfig'
      load_balancers: [ 'ghes-elb' ]
      vpc_zone_identifier: [ 'subnet-351ece6c' ]
      # Tags are currently broken in Ansible ASG implementation
      # https://github.com/ansible/ansible-modules-core/issues/744
      #tags:
      #  - Name: 'GHES Ansible'
      #    propagate_at_launch: yes
    -
      role: ec2-elb
      name: 'ghes-elb'
      state: 'present'
      security_group_ids: [ 'sg-4fe0982a' ] # FIXME - lookup secgroup ID dynamically.
      subnets: [ 'subnet-341ece6d' ]
      listeners:
        - protocol: http
          load_balancer_port: 80
          instance_port: 80
        - protocol: tcp
          load_balancer_port: 443
          instance_port: 443
        - protocol: tcp
          load_balancer_port: 8443
          instance_port: 8443
      health_check:
        ping_protocol: tcp
        ping_port: 80
        #ping_path: "/index.html"
        response_timeout: 5
        interval: 30
        unhealthy_threshold: 2
        healthy_threshold: 10
    #- cloudwatch-alarm
