---
- name: create ec2 secgroup
  local_action:
    module: ec2_group
    description: "{{ group_description }}"
    name: "{{ group_name }}"
    region: "{{ region }}"
    rules: "{{ group_rules }}"
    vpc_id: "{{ vpc_id }}"
  register: ec2_group_info
  
- name: create ec2 instance
  local_action:
    module: ec2
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    keypair: "{{ keypair }}"
    count_tag: "{{ count_tag }}"
    exact_count: "{{ exact_count }}"
    instance_tags: "{{ instance_tags }}"
    region: "{{ region }}"
    group_id: "{{ item }}"
    user_data: "{{ user_data }}"
    wait: true
    vpc_subnet_id: "{{ vpc_subnet }}"
  register: ec2_info
  with_items: ec2_group_info.group_id

- name: Set the fact for EC2 Instance variable
  set_fact: ec2_instance_ids="{{ item.instance_ids }}"
  with_items: ec2_info.results

- name: create EIP and assign to instance
  local_action:
    module: ec2_eip
    in_vpc: "{{ eip_in_vpc }}"
    instance_id: "{{ item }}"
    region: "{{ region }}"
  register: ec2_eip_info
  with_items: ec2_instance_ids
  
- debug: var=ec2_group_info
- debug: var=ec2_info
- debug: var=ec2_instance
