---
- name: create ec2 launch configuration
  ec2_lc:
    name: "{{ name }}"
    assign_public_ip: "{{ assign_public_ip }}"
    image_id: "{{ image_id }}"
    instance_monitoring: "{{ instance_monitoring }}"
    instance_profile_name: "{{ instance_profile_name | default(omit) }}"
    instance_type: "{{ instance_type }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    security_groups: "{{ security_groups | default(omit) }}"
    state: "{{ state }}"
    user_data: "{{ user_data | default(omit) }}"
    volumes: "{{ volumes | default(omit) }}"
  register: ec2_lc_info

- debug: var=ec2_lc_info
